apiVersion: v2
name: external-secrets-stack
description: Helm chart for fully configuring a cilium cluster.
type: application
version: 0.0.1
appVersion: 1.14.0-snapshot.3
keywords:
  - fluent
  - fluentd
  - fluent bit
  - logging
  - aggregator
home: https://fluentbit.io/
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/fluentd/fluentbit/icon/fluentbit-icon-color.svg
dependencies:
  - name: cert-manager
    version: "^1.12.1"
    repository: https://charts.jetstack.io
  - name: cilium
    version: "^1.14.0-snapshot.3"
    repository: https://helm.cilium.io
  - name: metallb
    version: "^0.13.10"
    repository: https://metallb.github.io/metallb
  - name: metrics-server
    version: "^3.10.0"
    repository: https://kubernetes-sigs.github.io/metrics-server
  - name: local-path-provisioner
    repository: https://charts.containeroo.ch
    version: "^0.0.24"
  - name: minio
    version: "^4.0.12"
    repository: https://charts.min.io
    condition: minio.enabled
  - name: kube-prometheus-stack
    version: "^46.8.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    tags:
      - monitoring
  - name: fluent-bit
    condition: fluent-bit.enabled
    repository: https://fluent.github.io/helm-charts
    version: "^0.30.4"
    tags:
      - logging
  - name: loki
    condition: loki.enabled
    repository: https://grafana.github.io/helm-charts
    version: "^2.15.2"
    tags:
      - logging
  - name: tempo
    condition: tempo.enabled
    repository: https://grafana.github.io/helm-charts
    version: "^1.3.1"
    tags:
      - logging
  - name: mimir-distributed
    condition: mimir.enabled
    repository: https://grafana.github.io/helm-charts
    version: "^4.5.0-weekly.241"
    tags:
      - monitoring
      - distributed
maintainers:
  - name: appkins
    email: nbatkins@gmail.com
    url: https://github.com/appkins
annotations:
  artifacthub.io/alternativeName: external-secrets-stack
  artifacthub.io/changes: |
    - kind: fixed
      description: "Fixed volume mount typo."
    - kind: fixed
      description: "Fixed missing fsGroup from pod security context."
